from root.application.interfaces.athlete_repository import AthleteRepository
from root.application.interfaces.db_interface import DBInterface
from root.application.interfaces.team_repository import TeamRepository