from enum import Enum

class SportRank(Enum):
    HONORED_MASTER_OF_SPORT_RUSSIA = "змс"
    MASTER_OF_SPORT_RUSSIA_OF_INTERNATIONAL_CLASS = "мсмк"
    MASTER_OF_SPORT_RUSSIA = "мс"
    CANDIDATE_MASTER_OF_SPORT_RUSSIA = "кмс"
    FIRST_SPORT_DEGREE = "1 ср"
    SECOND_SPORT_DEGREE = "2 ср"
    THIRD_SPORT_DEGREE = "3 ср"
    FIRST_YOUTH_DEGREE = "1 ср"
    SECOND_YOUTH_DEGREE = "2 юр"
    THIRD_YOUTH_DEGREE = "3 юр"
    NO_RANK = "бр"